services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=portfolio_db
      - MYSQL_USER=portfolio_user
      - MYSQL_PASSWORD=portfolio_pass
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  portfolio-app:
    build: .
    container_name: portfolio-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/portfolio_db
      - SPRING_DATASOURCE_USERNAME=portfolio_user
      - SPRING_DATASOURCE_PASSWORD=portfolio_pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  mysql-data:
