name: Thử nghiệm file README
on:
  push:
    branches: ["main"]

jobs:
  thuc_hanh_doc_file:
    runs-on: ubuntu-latest

    steps:
      - name: Buoc 1 - Xin chao
        run: echo "Hello Hutech"

      - name: Buoc 2 - Tai code
        uses: actions/checkout@v6

      - name: Buoc 3 - Doc file
        run: cat README.md
